go.property("character", hash("stranger"))
local npc = require("things.npc.characters")

function init(self)
	self.dia = 1
	self.int = 1
	print(npc[self.character]["item"])
end


function on_message(self, message_id, message, sender)
	if message_id == hash("interact") then
		if message.stuff[npc[self.character]["item"]] == true then
			print("Has Item")
		else
			print("Still needs item")
		end
	end
end



--if npc[self.character]["A"][self.dia][self.int] then
--	msg.post("/hud#hud", "show_text", {type = hash("dialog"), content = npc.text[self.dia][self.int]})
--	self.int = self.int+1
--else
--	msg.post("/hud#hud", "hide_text")
--	self.int = 1
--	if npc.text[self.dia+1] then
--		self.dia = self.dia+1
--	end
--end