function init(self)
	self.background = gui.get_node("textbox_background")
	self.border = gui.get_node("textbox_border")
	self.text = gui.get_node("textbox_text")

	gui.set_visible(self.background, false)
	gui.set_visible(self.border, false)
	gui.set_visible(self.text, false)
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	if message_id == hash("show_text") then
		gui.set_text(self.text, message.text)
		gui.set_visible(self.background, true)
		gui.set_visible(self.border, true)
		gui.set_visible(self.text, true)

	elseif message_id == hash("hide_text") then
		gui.set_visible(self.background, false)
		gui.set_visible(self.border, false)
		gui.set_visible(self.text, false)
	end
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
